# Setup
title:               Ryan Singh Sareen
tagline:             ''
description:         'Explorer. Learner. Following curiosity.'
url:                 https://ryanssareen.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
future:              true

# About/contact
author:
  name:              Ryan Singh Sareen
  url:
  email:             ryanssareen@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Collections
collections:
  articles:
    output: true
    permalink: /articles/:title/

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
